### ISSUE TITLE
Handle is not initialized

### ISSUE THREAD

**Issue by albertotono** [ladybug-tools/butterfly#238]
I have run like admin
ERROR:
	Handle is not initialized.

If you think this is a bug submit an issue on github.
https://github.com/ladybug-analysis-tools/honeybee-plus/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<string>", line 28, in main
  File "C:\Users\bimon\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Butterfly\extra\butterfly\windtunnel.py", line 241, in save
    _case = self.toOpenFOAMCase(make2dParameters)
  File "C:\Users\bimon\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Butterfly\extra\butterfly_dynamo\windtunnel.py", line 90, in toOpenFOAMCase
    return Case.fromWindTunnel(self, make2dParameters)
  File "C:\Users\bimon\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Butterfly\extra\butterfly\case.py", line 273, in fromWindTunnel
    _case = cls.fromBFGeometries(
  File "C:\Users\bimon\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Butterfly\extra\butterfly\case.py", line 228, in fromBFGeometries
    snappyHexMeshDict = SnappyHexMeshDict.fromBFGeometries(
  File "C:\Users\bimon\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Butterfly\extra\butterfly\snappyHexMeshDict.py", line 123, in fromBFGeometries
    _cls.setnSurfaceLayers()
  File "C:\Users\bimon\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Butterfly\extra\butterfly\snappyHexMeshDict.py", line 322, in setnSurfaceLayers
    layers = getSnappyHexMeshSurfaceLayers(self.geometries)
  File "C:\Users\bimon\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Butterfly\extra\butterfly\utilities.py", line 239, in getSnappyHexMeshSurfaceLayers
    _ref = OrderedDict()
  File "C:\Program Files (x86)\IronPython 2.7\Lib\collections.py", line 51, in __init__
    self.__update(*args, **kwds)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\abc.py", line 151, in __subclasscheck__
    if subclass in cls._abc_cache:
  File "C:\Program Files (x86)\IronPython 2.7\Lib\_weakrefset.py", line 73, in __contains__
    return wr in self.data
SystemError: Handle is not initialized.

**Comment by albertotono** [comment]
I restarted the pc and it works now. Thanks.
